<font size = 4 face = "黑体">

所有不是RuntimeException的异常，统称为Checked Exception，又被称为“已检查异常”，如IOException、SQLException等以及用户自定义的Exception异常。 这类异常在编译时就必须做出处理，否则无法通过编译。



![CheckedException异常](https://img-blog.csdnimg.cn/2020020215053458.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQzODA4NzAw,size_16,color_FFFFFF,t_70)




</br></br></br>

以上异常的处理办法:

```java
package yzy.exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream; 

public class testCheckedException {
	public static void main(String[] args) throws FileNotFoundException {
		InputStream is = new FileInputStream("D:\\a.txt");
		//1. throws声明异常
	
		
		try {
			InputStream is2 = new FileInputStream("D:\\a.txt");
		} catch (FileNotFoundException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}	
		//2. try/catch	
	}
}

```



</br>

总结: </br>
异常的处理方式有两种：</br>
使用“try/catch”捕获异常、</br>
使用“throws”声明异常。

<font color = #00ffff>
关于异常处理请看继续阅读后续的文章:
</font>

</font>